### ISSUE TITLE
Update DotGraphTracer event with success parameter 

### ISSUE THREAD

**Issue by alistairjevans** [autofac/Autofac.Diagnostics.DotGraph#7]
In core Autofac, we just added a new constructor parameter to the `OperationComplete` event args.

Need to update this package with the same before we release it.

**Comment by tillig** [comment]
Resolved by https://github.com/autofac/Autofac.Diagnostics.DotGraph/commit/77b148c9ae088c358a46e9a807583e2d45d96e9b
